language: python
python:
    - "3.6"

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - mkdir deps
  - mkdir deps/bin
  - mkdir deps/lib
  - mkdir deps/include
  - cd deps
  - git clone https://github.com/rdaly525/coreir.git
  - cd coreir
  - export COREIRCONFIG="g++-4.9"
  - export COREIR=$PWD
  - make install prefix=$TRAVIS_BUILD_DIR/deps
  - cd ..
  - cd ..
  - export PATH=$TRAVIS_BUILD_DIR/deps/bin:$PATH
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/deps/lib:$LD_LIBRARY_PATH
  - pip install coreir

install: 
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  # - "pip install codecov"

script: 
  - pip install -e .
  - export MANTLE=lattice
  - pytest --cov=silica
  - export MANTLE=coreir
  - pytest --cov=silica

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
